{
 "title": "VPA recommender",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "step", "label": "step", "query": { "query": "label_values(step)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vpa_recommender_vpa_objects_count,namespace)"
    }
   },
   {
    "name": "vpa",
    "query": {
     "query": "label_values(vpa_recommender_vpa_objects_count{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total VPA objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "vpa",
   "targets": [
    {
     "expr": "sum(vpa_recommender_vpa_objects_count{unsupported_config=\"true\", pod=\"$vpa\"})",
     "legendFormat": "Unsupported config"
    },
    {
     "expr": "sum(vpa_recommender_vpa_objects_count{matches_pods=\"false\", pod=\"$vpa\"})",
     "legendFormat": "Not matching Pods"
    },
    {
     "expr": "sum(vpa_recommender_vpa_objects_count{matches_pods=\"true\", pod=\"$vpa\"})",
     "legendFormat": "Matching Pods"
    }
   ]
  },
  {
   "title": "Total VPA objects",
   "type": "stat",
   "description": "Number of VPA objects present in the cluster",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpa_recommender_vpa_objects_count{pod=\"$vpa\"})"
    }
   ]
  },
  {
   "title": "Aggregate container states",
   "type": "stat",
   "description": "Number of aggregate container states being tracked by the recommender",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpa_recommender_aggregate_container_states_count{pod=\"$vpa\"})"
    }
   ]
  },
  { "title": "Execution Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Recommender execution latency, Step=$step",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "repeat": "step",
   "targets": [
    {
     "expr": "sum(rate(vpa_recommender_execution_latency_seconds_bucket{step=\"$step\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Recommendation general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Time to first recommendation",
   "type": "heatmap",
   "description": " Time elapsed from creating a valid VPA configuration to the first recommendation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(vpa_recommender_recommendation_latency_seconds_bucket{pod=\"$vpa\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Recommendations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing memory recommendations",
     "type": "timeseries",
     "description": "Count of usage samples when a recommendation should be present but is missing",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(vpa_quality_usage_sample_missing_recommendation_count{resource=\"memory\", pod=\"$vpa\"}\n[$__rate_interval])",
       "legendFormat": "OOM={{is_oom}}, Update Mode={{update_mode}}"
      }
     ]
    },
    {
     "title": "Memory usage recommendation relative diffs",
     "type": "heatmap",
     "description": "Diffs between recommendation and usage, normalized by recommendation value",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_usage_recommendation_relative_diffs_bucket{resource=\"memory\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Absolute memory diff when recommendation > usage",
     "type": "heatmap",
     "description": "Absolute diffs between recommendation and usage for memory when recommendation > usage",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_mem_recommendation_over_usage_diffs_bytes_bucket{recommendation_missing=\"false\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Absolute memory diff when recommendation <= usage",
     "type": "heatmap",
     "description": "Absolute diffs between recommendation and usage for memory when recommendation <= usage",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_mem_recommendation_lower_equal_usage_diffs_bytes_bucket{recommendation_missing=\"false\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Recommendations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing CPU recommendations",
     "type": "timeseries",
     "description": "Count of usage samples when a recommendation should be present but is missing",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "rate(vpa_quality_usage_sample_missing_recommendation_count{resource=\"cpu\", pod=\"$vpa\"}\n[$__rate_interval])",
       "legendFormat": "Update Mode={{update_mode}}"
      }
     ]
    },
    {
     "title": "CPU usage recommendation relative diffs",
     "type": "heatmap",
     "description": "Diffs between recommendation and usage, normalized by recommendation value",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_usage_recommendation_relative_diffs_bucket{resource=\"cpu\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Absolute CPU diff when recommendation > usage",
     "type": "heatmap",
     "description": "Absolute diffs between recommendation and usage for CPU when recommendation >  usage",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_cpu_recommendation_over_usage_diffs_cores_bucket{recommendation_missing=\"false\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Absolute CPU diff when recommendation <= usage",
     "type": "heatmap",
     "description": "Absolute diffs between recommendation and usage for CPU when recommendation <= usage",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "sum(rate(vpa_quality_cpu_recommendation_lower_equal_usage_diffs_cores_bucket{recommendation_missing=\"false\", pod=\"$vpa\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}